<?php

namespace App\Support\GeoIp;

final class CountryCatalog
{
    /**
     * @return array{name: string, lat: float, lng: float}|null
     */
    public static function find(string $code): ?array
    {
        $countries = self::countries();

        return $countries[strtoupper($code)] ?? null;
    }

    /**
     * @return array<string, array{name: string, lat: float, lng: float}>
     */
    public static function countries(): array
    {
        return [
            'AD' => ['name' => 'Andorra', 'lat' => 42.5, 'lng' => 1.5],
            'AE' => ['name' => 'United Arab Emirates', 'lat' => 24.0, 'lng' => 54.0],
            'AF' => ['name' => 'Afghanistan', 'lat' => 33.0, 'lng' => 66.0],
            'AL' => ['name' => 'Albania', 'lat' => 41.0, 'lng' => 20.0],
            'AM' => ['name' => 'Armenia', 'lat' => 40.2, 'lng' => 45.0],
            'AO' => ['name' => 'Angola', 'lat' => -12.5, 'lng' => 18.5],
            'AR' => ['name' => 'Argentina', 'lat' => -34.0, 'lng' => -64.0],
            'AT' => ['name' => 'Austria', 'lat' => 47.3, 'lng' => 13.3],
            'AU' => ['name' => 'Australia', 'lat' => -25.0, 'lng' => 134.0],
            'AZ' => ['name' => 'Azerbaijan', 'lat' => 40.5, 'lng' => 47.5],
            'BA' => ['name' => 'Bosnia and Herzegovina', 'lat' => 44.0, 'lng' => 18.0],
            'BD' => ['name' => 'Bangladesh', 'lat' => 24.0, 'lng' => 90.0],
            'BE' => ['name' => 'Belgium', 'lat' => 50.5, 'lng' => 4.5],
            'BG' => ['name' => 'Bulgaria', 'lat' => 42.7, 'lng' => 25.3],
            'BH' => ['name' => 'Bahrain', 'lat' => 26.0, 'lng' => 50.5],
            'BO' => ['name' => 'Bolivia', 'lat' => -17.0, 'lng' => -65.0],
            'BR' => ['name' => 'Brazil', 'lat' => -10.0, 'lng' => -55.0],
            'BY' => ['name' => 'Belarus', 'lat' => 53.0, 'lng' => 28.0],
            'CA' => ['name' => 'Canada', 'lat' => 56.0, 'lng' => -106.0],
            'CH' => ['name' => 'Switzerland', 'lat' => 47.0, 'lng' => 8.0],
            'CI' => ['name' => 'Côte d’Ivoire', 'lat' => 8.0, 'lng' => -5.5],
            'CL' => ['name' => 'Chile', 'lat' => -30.0, 'lng' => -71.0],
            'CM' => ['name' => 'Cameroon', 'lat' => 6.0, 'lng' => 12.5],
            'CN' => ['name' => 'China', 'lat' => 35.0, 'lng' => 105.0],
            'CO' => ['name' => 'Colombia', 'lat' => 4.0, 'lng' => -72.0],
            'CR' => ['name' => 'Costa Rica', 'lat' => 10.0, 'lng' => -84.0],
            'CY' => ['name' => 'Cyprus', 'lat' => 35.0, 'lng' => 33.0],
            'CZ' => ['name' => 'Czechia', 'lat' => 49.8, 'lng' => 15.5],
            'DE' => ['name' => 'Germany', 'lat' => 51.0, 'lng' => 10.0],
            'DK' => ['name' => 'Denmark', 'lat' => 56.0, 'lng' => 10.0],
            'DO' => ['name' => 'Dominican Republic', 'lat' => 19.0, 'lng' => -70.7],
            'DZ' => ['name' => 'Algeria', 'lat' => 28.0, 'lng' => 3.0],
            'EC' => ['name' => 'Ecuador', 'lat' => -1.8, 'lng' => -78.2],
            'EE' => ['name' => 'Estonia', 'lat' => 59.0, 'lng' => 26.0],
            'EG' => ['name' => 'Egypt', 'lat' => 26.0, 'lng' => 30.0],
            'ES' => ['name' => 'Spain', 'lat' => 40.0, 'lng' => -4.0],
            'ET' => ['name' => 'Ethiopia', 'lat' => 9.0, 'lng' => 39.5],
            'FI' => ['name' => 'Finland', 'lat' => 64.0, 'lng' => 26.0],
            'FR' => ['name' => 'France', 'lat' => 46.2, 'lng' => 2.2],
            'GB' => ['name' => 'United Kingdom', 'lat' => 54.0, 'lng' => -2.0],
            'GE' => ['name' => 'Georgia', 'lat' => 42.0, 'lng' => 43.5],
            'GH' => ['name' => 'Ghana', 'lat' => 8.0, 'lng' => -1.2],
            'GR' => ['name' => 'Greece', 'lat' => 39.0, 'lng' => 22.0],
            'GT' => ['name' => 'Guatemala', 'lat' => 15.5, 'lng' => -90.3],
            'HK' => ['name' => 'Hong Kong', 'lat' => 22.4, 'lng' => 114.1],
            'HR' => ['name' => 'Croatia', 'lat' => 45.1, 'lng' => 15.2],
            'HU' => ['name' => 'Hungary', 'lat' => 47.0, 'lng' => 19.5],
            'ID' => ['name' => 'Indonesia', 'lat' => -5.0, 'lng' => 120.0],
            'IE' => ['name' => 'Ireland', 'lat' => 53.4, 'lng' => -8.0],
            'IL' => ['name' => 'Israel', 'lat' => 31.5, 'lng' => 34.8],
            'IN' => ['name' => 'India', 'lat' => 21.0, 'lng' => 78.0],
            'IQ' => ['name' => 'Iraq', 'lat' => 33.0, 'lng' => 44.0],
            'IR' => ['name' => 'Iran', 'lat' => 32.0, 'lng' => 53.0],
            'IS' => ['name' => 'Iceland', 'lat' => 65.0, 'lng' => -18.0],
            'IT' => ['name' => 'Italy', 'lat' => 42.8, 'lng' => 12.8],
            'JM' => ['name' => 'Jamaica', 'lat' => 18.2, 'lng' => -77.3],
            'JO' => ['name' => 'Jordan', 'lat' => 31.0, 'lng' => 36.0],
            'JP' => ['name' => 'Japan', 'lat' => 36.0, 'lng' => 138.0],
            'KE' => ['name' => 'Kenya', 'lat' => 1.0, 'lng' => 38.0],
            'KH' => ['name' => 'Cambodia', 'lat' => 12.5, 'lng' => 105.0],
            'KR' => ['name' => 'South Korea', 'lat' => 36.5, 'lng' => 127.8],
            'KW' => ['name' => 'Kuwait', 'lat' => 29.3, 'lng' => 47.5],
            'KZ' => ['name' => 'Kazakhstan', 'lat' => 48.0, 'lng' => 68.0],
            'LB' => ['name' => 'Lebanon', 'lat' => 33.9, 'lng' => 35.9],
            'LK' => ['name' => 'Sri Lanka', 'lat' => 7.0, 'lng' => 81.0],
            'LT' => ['name' => 'Lithuania', 'lat' => 55.2, 'lng' => 24.0],
            'LU' => ['name' => 'Luxembourg', 'lat' => 49.8, 'lng' => 6.1],
            'LV' => ['name' => 'Latvia', 'lat' => 57.0, 'lng' => 25.0],
            'MA' => ['name' => 'Morocco', 'lat' => 32.0, 'lng' => -6.0],
            'MD' => ['name' => 'Moldova', 'lat' => 47.0, 'lng' => 29.0],
            'ME' => ['name' => 'Montenegro', 'lat' => 42.5, 'lng' => 19.3],
            'MG' => ['name' => 'Madagascar', 'lat' => -20.0, 'lng' => 47.0],
            'MK' => ['name' => 'North Macedonia', 'lat' => 41.6, 'lng' => 21.7],
            'ML' => ['name' => 'Mali', 'lat' => 17.0, 'lng' => -4.0],
            'MM' => ['name' => 'Myanmar', 'lat' => 21.0, 'lng' => 96.0],
            'MN' => ['name' => 'Mongolia', 'lat' => 46.0, 'lng' => 105.0],
            'MT' => ['name' => 'Malta', 'lat' => 35.9, 'lng' => 14.4],
            'MX' => ['name' => 'Mexico', 'lat' => 23.0, 'lng' => -102.0],
            'MY' => ['name' => 'Malaysia', 'lat' => 4.2, 'lng' => 108.0],
            'NG' => ['name' => 'Nigeria', 'lat' => 10.0, 'lng' => 8.0],
            'NL' => ['name' => 'Netherlands', 'lat' => 52.3, 'lng' => 5.5],
            'NO' => ['name' => 'Norway', 'lat' => 62.0, 'lng' => 10.0],
            'NP' => ['name' => 'Nepal', 'lat' => 28.0, 'lng' => 84.0],
            'NZ' => ['name' => 'New Zealand', 'lat' => -41.0, 'lng' => 174.0],
            'OM' => ['name' => 'Oman', 'lat' => 21.0, 'lng' => 57.0],
            'PA' => ['name' => 'Panama', 'lat' => 8.5, 'lng' => -80.0],
            'PE' => ['name' => 'Peru', 'lat' => -10.0, 'lng' => -76.0],
            'PH' => ['name' => 'Philippines', 'lat' => 13.0, 'lng' => 122.0],
            'PK' => ['name' => 'Pakistan', 'lat' => 30.0, 'lng' => 70.0],
            'PL' => ['name' => 'Poland', 'lat' => 52.0, 'lng' => 20.0],
            'PR' => ['name' => 'Puerto Rico', 'lat' => 18.2, 'lng' => -66.5],
            'PT' => ['name' => 'Portugal', 'lat' => 39.5, 'lng' => -8.0],
            'PY' => ['name' => 'Paraguay', 'lat' => -23.4, 'lng' => -58.4],
            'QA' => ['name' => 'Qatar', 'lat' => 25.3, 'lng' => 51.2],
            'RE' => ['name' => 'Réunion', 'lat' => -21.1, 'lng' => 55.5],
            'RO' => ['name' => 'Romania', 'lat' => 46.0, 'lng' => 25.0],
            'RS' => ['name' => 'Serbia', 'lat' => 44.0, 'lng' => 21.0],
            'RU' => ['name' => 'Russia', 'lat' => 60.0, 'lng' => 100.0],
            'SA' => ['name' => 'Saudi Arabia', 'lat' => 24.0, 'lng' => 45.0],
            'SE' => ['name' => 'Sweden', 'lat' => 62.0, 'lng' => 15.0],
            'SG' => ['name' => 'Singapore', 'lat' => 1.35, 'lng' => 103.8],
            'SI' => ['name' => 'Slovenia', 'lat' => 46.1, 'lng' => 14.8],
            'SK' => ['name' => 'Slovakia', 'lat' => 48.7, 'lng' => 19.5],
            'SN' => ['name' => 'Senegal', 'lat' => 14.5, 'lng' => -14.5],
            'SV' => ['name' => 'El Salvador', 'lat' => 13.8, 'lng' => -88.9],
            'TH' => ['name' => 'Thailand', 'lat' => 15.5, 'lng' => 101.0],
            'TN' => ['name' => 'Tunisia', 'lat' => 34.0, 'lng' => 9.0],
            'TR' => ['name' => 'Turkey', 'lat' => 39.0, 'lng' => 35.0],
            'TW' => ['name' => 'Taiwan', 'lat' => 23.7, 'lng' => 121.0],
            'TZ' => ['name' => 'Tanzania', 'lat' => -6.4, 'lng' => 35.0],
            'UA' => ['name' => 'Ukraine', 'lat' => 49.0, 'lng' => 32.0],
            'UG' => ['name' => 'Uganda', 'lat' => 1.4, 'lng' => 32.3],
            'US' => ['name' => 'United States', 'lat' => 38.0, 'lng' => -97.0],
            'UY' => ['name' => 'Uruguay', 'lat' => -33.0, 'lng' => -56.0],
            'UZ' => ['name' => 'Uzbekistan', 'lat' => 41.4, 'lng' => 64.6],
            'VE' => ['name' => 'Venezuela', 'lat' => 8.0, 'lng' => -66.0],
            'VN' => ['name' => 'Vietnam', 'lat' => 16.0, 'lng' => 108.0],
            'YE' => ['name' => 'Yemen', 'lat' => 15.5, 'lng' => 48.0],
            'ZA' => ['name' => 'South Africa', 'lat' => -29.0, 'lng' => 25.0],
            'ZM' => ['name' => 'Zambia', 'lat' => -15.0, 'lng' => 30.0],
            'ZW' => ['name' => 'Zimbabwe', 'lat' => -19.0, 'lng' => 30.0],
        ];
    }
}
